[workspace]
resolver = "3"
members = [
    "crates/stano-axum",
    "crates/stano-common",
    "crates/stano-di",
    "crates/stano-di-macros",
    "crates/stano-example-app/domain",
    "crates/stano-example-app/security",
    "crates/stano-example-app/infrastructure",
    "crates/stano-example-app/services",
    "crates/stano-example-app/rest-api",
    "crates/stano-example-app/launcher",
    "crates/stano-launcher",
    "crates/stano-route-macros",
    "crates/stano-seaorm",
    "crates/stano-security",
    "crates/stano-starter",
    "crates/stano-starter-domain",
    "crates/stano-starter-rest",
    "crates/stano-starter-service",
]

[workspace.package]
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jstano/modular-rust-platform"
homepage = "https://github.com/jstano/modular-rust-platform"

[workspace.dependencies]
stano-common = { path = "crates/stano-common", version = "0.1.0" }
stano-di = { path = "crates/stano-di", version = "0.1.0" }
stano-di-macros = { path = "crates/stano-di-macros", version = "0.1.0" }
stano-route-macros = { path = "crates/stano-route-macros", version = "0.1.0" }
stano-security = { path = "crates/stano-security", version = "0.1.0" }
stano-axum = { path = "crates/stano-axum", version = "0.1.0" }
stano-launcher = { path = "crates/stano-launcher", version = "0.1.0" }
stano-seaorm = { path = "crates/stano-seaorm", version = "0.1.0" }
stano-starter = { path = "crates/stano-starter", version = "0.1.0" }
stano-starter-domain = { path = "crates/stano-starter-domain", version = "0.1.0" }
stano-starter-rest = { path = "crates/stano-starter-rest", version = "0.1.0" }
stano-starter-service = { path = "crates/stano-starter-service", version = "0.1.0" }
