[package]
name = "stano-di-macros"
version.workspace = true
edition = "2024"
description = "Proc macros (#[component], #[service]) that generate boilerplate and auto-register components for stano-di"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/stano-di-macros"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.42"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
proc-macro-crate = "3"

[dev-dependencies]
trybuild = "1"
stano-di = { workspace = true }
