[package]
name = "stano-example-services"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
stano-example-domain = { path = "../domain" }
stano-common = { path = "../../stano-common" }
stano-di = { path = "../../stano-di" }
stano-di-macros = { path = "../../stano-di-macros" }
async-trait = "0.1"
